image: node:latest

stages:
   - clean
   - build
   - test
   - deploy
   - BEstShit

#Lets define a job with for every stage.
jobCleaning:
   stage: clean
   script:
      - echo "Cleaning the code"
jobBuilding:
   stage: build
   script:
      - npm install
   cache:
      paths:
      - node_modules/
   artifacts:
     paths:
       - lab1-vicbe572-erian599.pdf
       - node_modules/
jobTesting:
   stage: test
   script:
      - npm test
jobDeploying:
   stage: deploy
      - echo "Deploying the code"

BestSHitDeploying:
  stage: BEstShit
  script:
    - echo "Fungerar?"
