#stages can be declared using a keyword stages. You can add any number of stages as you require.
stages:
   - clean
   - build
   - test
   - deploy
#Lets define a job with for every stage.
jobCleaning:
   stage: clean # This tag tells gitlab to run this job only for clean stage
   script:
      - echo "Cleaning the code"
jobBuilding:
   stage: build # This tag tells gitlab to run this job only for build stage
   script:
      - echo "Building the app!"
jobTesting:
   stage: test # This tag tells gitlab to run this job only for test stage
   script:
      - npm install
      - npm test
jobDeploying:
   stage: deploy # This tag tells gitlab to run this job only for deploy stage
   script:
      - echo "Deploying the code"
