image: node:latest
cache:
  paths:
  - node_modules/

stages:
   - clean
   - build
   - test
   - deploy
   - artifacts

artifacts:
  paths:
    - .lab1-vicbe572-erian599.pdf
    
#Lets define a job with for every stage.
jobCleaning:
   stage: clean # This tag tells gitlab to run this job only for clean stage
   script:
      - echo "Cleaning the code"
jobBuilding:
   stage: build # This tag tells gitlab to run this job only for build stage
   script:
      - npm install
jobTesting:
   stage: test # This tag tells gitlab to run this job only for test stage
   script:
      - npm test
jobDeploying:
   stage: deploy # This tag tells gitlab to run this job only for deploy stage
   script:
      - echo "Deploying the code"
