language: node_js
node_js:
  - "node"

addons:
  artifacts: true

cache: npm
jobs:
  include:
    - stage: clean
      script: echo "cleaning"
    - stage: build
      script: npm install
    - stage: test
      script: npm test
    - stage: deploy
      script: echo "deploying"
