jobs:
  include:
    - stage: clean
      script: echo "cleaning"
    - stage: build
      script: echo "building"
    - stage: test
      script: echo "testing"
    - stage: deploy
      script: echo "deploying"
