language: node_js
node_js:
  - "node"

cache: npm
jobs:
  include:
    - stage: clean
      script: echo "cleaning"
    - stage: build
      script: npm install
    - stage: test
      script: npm test
    - stage: deploy
      script: echo "deploying"
    - stage: Funky
      script: echo "Do the funky thing"
